[pytest]
markers =
    smoke: Быстрая проверка критического функционала
    regression: Полная регрессия
    idempotency: Тесты идемпотентности
    corner: Граничные случаи
    performance: Тесты производительности
testpaths = api_tests
addopts = -v --strict-markers --alluredir=allure-results --tb=short
timeout = 30